### ISSUE TITLE
For mobile manipulator EE calibration data collect

### ISSUE THREAD

**Issue by DiomandLEE** [utiasDSL/mobile_manipulation_central#1]
[here](https://github.com/utiasDSL/mobile_manipulation_central/blob/main/scripts/calibration/collect_arm_calibration_data.py#L216), 

1. Use quintic polynomials to connect two target configuration points to generate a trajectory, and then use feedforward PID to publish velocity. Why can't we use the target configuration as the position control input to reach the target configuration point, and instead choose to use velocity control?  

2. Why, when collecting data, is it necessary to keep the Ridgeback's target configuration point constant, always `home[:,3]`?  [here](https://github.com/utiasDSL/mobile_manipulation_central/blob/main/scripts/calibration/collect_arm_calibration_data.py#L155)

3. Can accurate calibration really be achieved by collecting only ten data points?  [here](https://github.com/utiasDSL/mobile_manipulation_central/blob/main/scripts/calibration/collect_arm_calibration_data.py#L31)

These are my three questions. Some of them might seem naive, but I would greatly appreciate it if you could explain. Thank you very much!

**Comment by adamheins** [comment]
1. Using a quintic polynomial is nice and smooth, but really you can get to the next target configuration however you want.
2. It isn't necessary for the base to remain stationary, but it also isn't necessary for it to move, since the transforms we're optimizing are invariant to the base's pose in the world (i.e., the transform between base and arm, and between arm and tray, do not change if the base's pose changes).
3. Sure, as long as the measurements aren't very noisy. If you had a non-negligible amount of noise in the measurements, then you would need more measurements in order to average it out. However, in our case, the 10 data points seemed to work fine.
